on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: 迁出代码
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@master

      # 安装Node10
      - name: 安装node.js
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.2

      # # 安装依赖
      # - name: 安装依赖
      #   run: npm install

      # 打包
      - name: 打包
        run: npm run build

      # 推送
      - name: 推送
        run:
          - cd /docs/.vuepress/dist #进入_book目录
          - git init
          - git remote add origin https://${REF} #设置要托管到的仓库名
          - git add . #添加_book目录下的所有文件
          - git commit -m "Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages"
          - git branch -M main
          - git push --force --quiet "https://${TOKEN}@${REF}" main:gh-pages #强制推送到gh-pages分支
